const sources={notice:{remote:'https://docs.google.com/spreadsheets/d/e/2PACX-1vTzfAyBr9vlYj4GdiBTdzygJ4nV717sxN-1tdr2bKNAGNCoUQdIOKdB9hCmxZx_2Dfudokj8vLaBMAP/pubhtml?gid=0&single=true',local:'./data/시골별님 아트머그 DB - 공지사항.csv'},process:{remote:'https://docs.google.com/spreadsheets/d/e/2PACX-1vTzfAyBr9vlYj4GdiBTdzygJ4nV717sxN-1tdr2bKNAGNCoUQdIOKdB9hCmxZx_2Dfudokj8vLaBMAP/pubhtml?gid=48581277&single=true',local:'./data/시골별님 아트머그 DB - 작업 과정.csv'},guide:{remote:'https://docs.google.com/spreadsheets/d/e/2PACX-1vTzfAyBr9vlYj4GdiBTdzygJ4nV717sxN-1tdr2bKNAGNCoUQdIOKdB9hCmxZx_2Dfudokj8vLaBMAP/pubhtml?gid=1320179304&single=true',local:'./data/시골별님 아트머그 DB - 과정 안내.csv'},portfolio:{remote:'https://docs.google.com/spreadsheets/d/e/2PACX-1vTzfAyBr9vlYj4GdiBTdzygJ4nV717sxN-1tdr2bKNAGNCoUQdIOKdB9hCmxZx_2Dfudokj8vLaBMAP/pubhtml?gid=1232235367&single=true',local:'./data/시골별님 아트머그 DB - 포트폴리오.csv'},collab:{remote:'https://docs.google.com/spreadsheets/d/e/2PACX-1vTzfAyBr9vlYj4GdiBTdzygJ4nV717sxN-1tdr2bKNAGNCoUQdIOKdB9hCmxZx_2Dfudokj8vLaBMAP/pubhtml?gid=258738929&single=true',local:'./data/시골별님 아트머그 DB - 협업 작가.csv'}};
const state={portfolio:[],activeCategory:''};
const $=selector=>document.querySelector(selector);
const $$=selector=>Array.from(document.querySelectorAll(selector));
const clean=value=>(value??'').toString().trim();
const escapeHtml=value=>clean(value).replace(/[&<>'"]/g,match=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[match]));
const toCsvUrl=url=>url.replace('/pubhtml','/pub').replace(/([?&])single=true(&?)/,'$1output=csv$2').replace(/[?&]$/,'');
const sortRows=(rows,keys)=>rows.sort((a,b)=>{for(const key of keys){const av=Number(a[key]||0);const bv=Number(b[key]||0);if(av!==bv)return av-bv}return 0});
function parseCsv(text){const rows=[];let row=[];let value='';let quoted=false;for(let i=0;i<text.length;i++){const char=text[i];const next=text[i+1];if(char==='"'){if(quoted&&next==='"'){value+='"';i++}else quoted=!quoted}else if(char===','&&!quoted){row.push(value);value=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')i++;row.push(value);if(row.some(cell=>cell!==''))rows.push(row);row=[];value=''}else value+=char}row.push(value);if(row.some(cell=>cell!==''))rows.push(row);const headers=(rows.shift()||[]).map(clean);return rows.map(cells=>Object.fromEntries(headers.map((header,index)=>[header,clean(cells[index])]))) }
async function loadCsv(key){const item=sources[key];try{const res=await fetch(toCsvUrl(item.remote),{cache:'no-store'});if(!res.ok)throw new Error('remote');const text=await res.text();if(/^\s*</.test(text))throw new Error('html');return parseCsv(text)}catch(error){const res=await fetch(item.local,{cache:'no-store'});return parseCsv(await res.text())}}
function imageUrl(url){const raw=clean(url);const match=raw.match(/drive\.google\.com\/file\/d\/([^/]+)/);if(match)return `https://lh3.googleusercontent.com/d/${match[1]}`;return raw}
function renderNotice(rows){const root=$('[data-render="notice"]');const data=sortRows(rows.filter(row=>row.content),['order']);root.innerHTML=data.map(row=>`<article class="notice-item"><span>${escapeHtml(row.order)}</span><p>${escapeHtml(row.content)}</p></article>`).join('')||'<div class="empty">등록된 공지사항이 없습니다.</div>'}
function renderProcess(rows){const root=$('[data-render="process"]');const data=sortRows(rows.filter(row=>row.name),['order']);root.innerHTML=data.map(row=>`<article class="process-step"><span>${escapeHtml(row.order)}</span><h3>${escapeHtml(row.name)}</h3></article>`).join('')||'<div class="empty">등록된 작업 과정이 없습니다.</div>'}
function groupBy(rows,key){return rows.reduce((acc,row)=>{const value=row[key]||'기타';(acc[value] ||= []).push(row);return acc},{})}
function renderGuide(rows){const root=$('[data-render="guide"]');const data=sortRows(rows.filter(row=>row.content),['category_order','order']);const grouped=groupBy(data,'category');root.innerHTML=Object.entries(grouped).map(([category,items])=>`<article class="guide-card"><h3>${escapeHtml(category)}</h3><ul>${items.map(item=>`<li>${escapeHtml(item.content)}</li>`).join('')}</ul></article>`).join('')||'<div class="empty">등록된 과정 안내가 없습니다.</div>'}
function getCategories(rows){const map=new Map();sortRows(rows.filter(row=>row.category),['category_order','order']).forEach(row=>{if(!map.has(row.category))map.set(row.category,row.category_order)});return Array.from(map.keys())}
function renderPortfolioTabs(){const root=$('[data-render="portfolio-tabs"]');const categories=getCategories(state.portfolio);if(!state.activeCategory)state.activeCategory=categories[0]||'';root.innerHTML=categories.map(category=>`<button class="tab-button" type="button" data-category="${escapeHtml(category)}" aria-selected="${category===state.activeCategory}">${escapeHtml(category)}</button>`).join('');root.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{state.activeCategory=button.dataset.category;renderPortfolio();document.querySelector('#samples').scrollIntoView({behavior:'smooth',block:'start'})}))}
function renderPortfolio(){renderPortfolioTabs();const root=$('[data-render="portfolio"]');const data=sortRows(state.portfolio.filter(row=>row.category===state.activeCategory&&row.img_url),['order']);root.innerHTML=data.map(row=>{const src=imageUrl(row.img_url);const title=row.title||row.category||'샘플';const desc=row.desc||'';return `<article class="sample-card" tabindex="0" role="button" data-full="${escapeHtml(src)}" data-title="${escapeHtml(title)}" data-desc="${escapeHtml(desc)}"><div class="sample-image"><img src="${escapeHtml(src)}" alt="${escapeHtml(title)}" loading="lazy"></div>${title||desc?`<div class="sample-info">${title?`<h3>${escapeHtml(title)}</h3>`:''}${desc?`<p>${escapeHtml(desc)}</p>`:''}</div>`:''}</article>`}).join('')||'<div class="empty">등록된 샘플이 없습니다.</div>';root.querySelectorAll('.sample-card').forEach(card=>{card.addEventListener('click',()=>openModal(card.dataset.full,card.dataset.title,card.dataset.desc));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' ')openModal(card.dataset.full,card.dataset.title,card.dataset.desc)})})}
function renderCollab(rows){const root=$('[data-render="collab"]');const data=sortRows(rows.filter(row=>row.name||row.thumb),['order']);root.innerHTML=data.map(row=>`<article class="collab-card"><div class="collab-thumb"><img src="${escapeHtml(imageUrl(row.thumb))}" alt="${escapeHtml(row.name)}" loading="lazy"></div><div><h3>${escapeHtml(row.name)}</h3><p>${escapeHtml(row.desc)}</p>${row.link?`<a href="${escapeHtml(row.link)}" target="_blank" rel="noopener noreferrer">페이지 보기</a>`:''}</div></article>`).join('')||'<div class="empty">등록된 협업 작가가 없습니다.</div>'}
function openModal(src,title,desc){$('[data-modal-image]').src=src;$('[data-modal-image]').alt=title||'샘플 이미지';$('[data-modal-caption]').textContent=[title,desc].filter(Boolean).join('\n');$('[data-modal]').classList.add('is-open');$('[data-modal]').setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
function closeModal(){$('[data-modal]').classList.remove('is-open');$('[data-modal]').setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');$('[data-modal-image]').src=''}
function showToast(text){const toast=$('[data-toast]');toast.textContent=text;toast.classList.add('is-show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('is-show'),1800)}
function setupModal(){$('[data-modal-close]').addEventListener('click',closeModal);$('[data-modal]').addEventListener('click',event=>{if(event.target.matches('[data-modal]'))closeModal()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()})}
function getFormValue(name){const field=$(`[data-request-form] [name="${name}"]`);return clean(field?.value)}
function buildRequestText(){const value=(name,placeholder)=>getFormValue(name)||placeholder;return `1. 신청 타입
${value('type','ex) 방송용 - 전신')}

2. 캐릭터 정보 및 외형
${value('character','캐릭터의 상세 정보와 외형을 작성해주세요. 또는 참고 이미지 및 자료를 첨부해주셔도 됩니다.')}
(자료 첨부 시 더욱 높은 퀄리티의 일러스트 작업이 가능합니다.)

3. 캐릭터 포즈 및 구도
${value('pose','원하시는 포즈와 구도를 작성해주세요. 또는 참고 이미지 및 자료를 첨부해주셔도 됩니다.')}
(자료 첨부 시 더욱 높은 퀄리티의 일러스트 작업이 가능합니다.)

4. 기타 요청사항
${value('extra','원하시는 일러스트의 분위기, 배경, 색감 등 중요 사항을 자유롭게 작성해주세요.')}

5. 방송 정보
${value('stream','닉네임과 송출 플랫폼을 함께 작성해주세요.')}

※ 오마카세 진행도 가능합니다.
오마카세의 경우, 캐릭터의 구도 및 분위기는 작가의 재량에 따라 작업됩니다.`}
function setupCopy(){$('[data-action="copy-form"]').addEventListener('click',async()=>{const text=buildRequestText();try{await navigator.clipboard.writeText(text);showToast('작성 내용이 복사되었습니다.')}catch(error){const area=document.createElement('textarea');area.value=text;document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();showToast('작성 내용이 복사되었습니다.')}});$('[data-request-form]').addEventListener('reset',()=>setTimeout(()=>showToast('작성 내용이 초기화되었습니다.'),0))}
async function init(){setupModal();setupCopy();const [notice,process,guide,portfolio,collab]=await Promise.all([loadCsv('notice'),loadCsv('process'),loadCsv('guide'),loadCsv('portfolio'),loadCsv('collab')]);renderNotice(notice);renderProcess(process);renderGuide(guide);state.portfolio=portfolio;renderPortfolio();renderCollab(collab)}
init().catch(()=>{document.body.insertAdjacentHTML('beforeend','<div class="toast is-show">데이터를 불러오지 못했습니다.</div>')});
